services:
  php:
    image: ghcr.io/dmkos/php:8.5-fpm-freebsd15-pkg
    restart: always
    volumes:
      - ./html:/usr/local/www/html
  web:
    build:
      context: .
      dockerfile: caddy.containerfile
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./config:/usr/local/etc/caddy
      - ./html:/usr/local/www/html
      - caddy_data:/var/db/caddy/data
      - caddy_config:/var/db/caddy/config

volumes:
  caddy_data:
  caddy_config:
